manifest = "43570b0a0a929eea37de486d0ada90327b843fa4bc9339ff9d57dac0835306ee"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-circular_buffer"
target = "//:circular_buffer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-serialization"
target = "//:serialization"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-unordered"
target = "//:unordered"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.69.0" ]
revision = "849f28ea3223b0440a6d378b19f3c66c1a539223"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.69.0" ]
revision = "3b931e6ca0a28b244f8692cf797ae3d4600c4b86"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.69.0" ]
revision = "8c356ca68338cb9dc02e762a7a6fab6972021619"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.69.0" ]
revision = "75f6806153c44eb2fe7257e73c4fe61423ba7171"

[lock."github.com/buckaroo-pm/boost-circular_buffer"]
versions = [ "1.69.0" ]
revision = "7528309bd16be53b3d9dfbe92e5676d946821ba7"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.69.0" ]
revision = "bcaa4ee0ffe9919a92cebc9f4d533f51bca21648"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.69.0" ]
revision = "789954938e5acfbba080099137a47434f1201cca"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.69.0" ]
revision = "13b5c4e06d419ba8f51b4dbcc864070978099e7e"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.69.0" ]
revision = "d38267954f10bed05fee712ad5aea58aa74816ad"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.69.0" ]
revision = "addd909479c7ff5496cea1039cdb8499c6391c79"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.69.0" ]
revision = "351e7234276fbfc8a8705acfde9b719583aa1634"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.69.0" ]
revision = "3824f04b4dcbfe6d7811927d71f257565204f704"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.69.0" ]
revision = "139738bc1cc3629761e7a5c706ffa036e8129f36"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "1.69.0" ]
revision = "e43777346e03a8c11d5edfbf8080170b93df3c51"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.69.0" ]
revision = "e84d6254809d39e5c5f9d3c31e206c247619e1e5"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.69.0" ]
revision = "5c7442dd488005a9ebb703d2db91d6acb519c2fb"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.69.0" ]
revision = "9142209a69d7832ff585bc8f81510fb4c830e212"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.69.0" ]
revision = "10b050c28d4205309794f9fbf17f3ffe306e97f0"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.69.0" ]
revision = "026118631ec37f5ffdaebf51cfc828abd3cbc44f"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.69.0" ]
revision = "6bea1dc657697f34e9e363770d961cda684a43c5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.69.0" ]
revision = "8f9b174b132f4366c11eb474785006fe157319ed"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.69.0" ]
revision = "7b9597e7b7dbe0d9f69166c44b7d51b19e6b2089"

[lock."github.com/buckaroo-pm/boost-serialization"]
versions = [ "1.69.0" ]
revision = "47f9da231b1281abcce2739d2516c79da5f1b247"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.69.0" ]
revision = "8263e5bac128e9356a3e321e3da52d75332c7a54"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.69.0" ]
revision = "43a1751b4cfbe193d0a7ae7c79601356e953b1f9"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.69.0" ]
revision = "d3686a31232da8d09e4e76d062d631ff7161334f"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.69.0" ]
revision = "03cd3f1eb5eafd71f46d492bbb119cb94d6e2954"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.69.0" ]
revision = "96566eb748e6dec02ab34491334d401e1e6adc7d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.69.0" ]
revision = "209f7a69bfa25411d9072c4ba9c15f800c9abdc4"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.69.0" ]
revision = "916573e9da1e36a7833b935a28340d8ddc225644"

[lock."github.com/buckaroo-pm/boost-unordered"]
versions = [ "1.69.0" ]
revision = "a2235cf4fe933f76a8aeb97af04ebdf80a30f6a3"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.69.0" ]
revision = "88a06d226cfbf7cc3559e78a236c04fe104029f2"
